# Numpy

🚀 1. What is NumPy? (The simplest explanation students understand)
NumPy = Numerical Python — a library for fast mathematical operations on large, homogeneous arrays.
It is the foundation for Pandas, SciPy, Scikit‑Learn, TensorFlow, PyTorch, etc.

Authoritative sources confirm:

NumPy provides N‑dimensional arrays (ndarray) and efficient operations on them .

It is widely used in science and engineering for high‑performance numerical computing .

Arrays are stored in contiguous memory, making them much faster than Python lists

In [1]:
# how to install numpy
# !pip install <package_name>
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# python list vs numpy array
import numpy as np
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print("List:", lst)
print("Numpy Array:", arr)


List: [1, 2, 3, 4, 5]
Numpy Array: [1 2 3 4 5]


In [3]:
# operations on numpy arrays
arr2 = arr * 2
print("Original Array:", arr)
print("Array after multiplication:", arr2)

Original Array: [1 2 3 4 5]
Array after multiplication: [ 2  4  6  8 10]


In [4]:
# same operation on python list gives different result, repeated items
lst2 = lst * 2
print("Original List:", lst)
print("List after multiplication:", lst2)

Original List: [1, 2, 3, 4, 5]
List after multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
lst = [1, 2, 3, 4, 5]
[x * 2 for x in lst]

[2, 4, 6, 8, 10]

In [6]:
a1 = np.array([1, 2, 3]) # 1D array
a2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
print("1D Array:\n", a1)
print("2D Array:\n", a2)


1D Array:
 [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
# create a 3D array of zeros
a3 = np.zeros((3, 3, 3))
print("3D Array of zeros:\n", a3)

3D Array of zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [8]:
a2 = np.zeros((3, 3))

In [9]:
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a2.shape

(3, 3)

In [11]:
# we could also do for ones
a4 = np.ones((2, 2))
print("2D Array of ones:\n", a4)

2D Array of ones:
 [[1. 1.]
 [1. 1.]]


In [12]:
# or use arrange
a5 = np.arange(0, 10, 2) # start, stop, step
print("Array with arange:\n", a5)
# gives one dimensional array with values from 0 to 10 with step of 2

Array with arange:
 [0 2 4 6 8]


In [13]:
# numpy array attributes
print("Shape of a2:", a2.shape)
print("Data type of a2:", a2.dtype)
print("Number of dimensions of a2:", a2.ndim)
print("Size of a2:", a2.size)

Shape of a2: (3, 3)
Data type of a2: float64
Number of dimensions of a2: 2
Size of a2: 9


In [14]:
# indexing and slicing in numpy arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", a)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
a[1, 0] # element at row 1, column 0

np.int64(4)

In [16]:
a[:, 1] # all rows, column 1

array([2, 5, 8])

In [17]:
a[0:2, 1:3] # rows 0 and 1, columns 1 and 2 submatrix

array([[2, 3],
       [5, 6]])

In [18]:
# broadcasting in numpy
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print("Array a+b:\n", a+b) # b is broadcasted to each row of a

Array a+b:
 [[11 22 33]
 [14 25 36]]


In [19]:
# mathematical operations on numpy arrays
arr = np.array([1, 2, 3, 4, 5])

arr.sum()

np.int64(15)

In [20]:
arr.mean()

np.float64(3.0)

In [21]:
arr.max()

np.int64(5)

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.std()

np.float64(1.4142135623730951)

In [24]:
# standardize the array
standardized_arr = (arr - arr.mean()) / arr.std()
print("Standardized Array:", standardized_arr)

Standardized Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
# 2D array: each row = [prob_class0, prob_class1]
probs = np.array([
    [0.12, 0.88],
    [0.67, 0.33],
    [0.49, 0.51],
    [0.91, 0.09],
    [0.55, 0.45]
])

print("Original probabilities:\n", probs)


Original probabilities:
 [[0.12 0.88]
 [0.67 0.33]
 [0.49 0.51]
 [0.91 0.09]
 [0.55 0.45]]


In [26]:
# we want to convert these probabilities to class labels (0 or 1) using a threshold of 0.5
threshold = 0.5

first_col = probs[:, 1]
print("First column:", first_col)

First column: [0.88 0.33 0.51 0.09 0.45]


In [27]:
(first_col > 0.5)

array([ True, False,  True, False, False])

In [28]:
binary_output = (first_col > 0.5).astype(int)
print("Binary output:", binary_output)

Binary output: [1 0 1 0 0]
